import os

from colorama import init
from colorama import Fore, Back, Style

import time

def cls():
    os.system('cls'if os.name=='nt'else 'clear')

print(Fore.GREEN)

cls()
print("  _     _   ___  | ___  |")
print(" / \   / \  |__  | |  \ |")
print("( B ) ( Y )    | | |_ / |")
print(" \_/   \_/  __ | | |  \ |")

print(Fore.BLUE)

print(Fore.MAGENTA)
print('_______________________________________')
print('Если не знаете какой то информации ставьте 0') 
print('В программе должен быть максимум один 0')
print('На логинe нельзя ставить 0')
print('_______________________________________')
print(Fore.BLUE)
a = input(" Login | Логин: ")
name = input("Name of victim | Имя атакуемого: ")
name1 = input('Lastname | Фамилия: ')
age = input("Bithyear | Год рождения: ")
data = input("Number of bithmouth | Номер месяца: ")
data1 = input("Number of bithday | Номер дня: ")

cls()
print("  _     _   ___  | ___  |")
print(" / \   / \  |__  | |  \ |")
print("( B ) ( Y )    | | |_ / |")
print(" \_/   \_/  __ | | |  \ |")

print(Fore.RED)

if name == "0":
    print("Обработка данных, подождите | Please wait...")
    time.sleep(3)

    print(Fore.YELLOW)

    print(a + ":" +  name1 + age)
    time.sleep(1)
    print(a + ":" + age + name1)
    time.sleep(1)
    print(a + ":" + data + name1)
    time.sleep(1)
    print(a + ":" + age + data + data1 + name1)
    time.sleep(1)
    print(a + ":" + age + data1 + data + name1)
    time.sleep(1)
    print(a + ":" + name1 + data1 + data)
    time.sleep(1)
    print(a + ":" + name1 + data + data1)
    time.sleep(1)
    print(a + ":" + age + data1 + data)
    time.sleep(1)
    print(a + ":" + age + data + data1)
    time.sleep(1)
    print(a + ":" + age + data1 + data)
    time.sleep(1)
    print(a + ":" + data1 + data + age)
    time.sleep(1)
    print(a + ":" + data + age + data1)
    time.sleep(1)
    print(a + ":" + age + age)
    time.sleep(1)
    print(a + ":" + name1 + name1)
    time.sleep(1)
    print(a + ":" + data + age)
    time.sleep(1)
    print(a + ":" + data1 + age)
    time.sleep(1)
    print(a + ":" + data + data1 + age)
    time.sleep(1)

if name1 == "0":
    print("Обработка данных, подождите | Please wait")
    time.sleep(3)

    print(Fore.YELLOW)

    print(a + ":" + name + age)
    time.sleep(1)
    print(a + ":" + age + name)
    time.sleep(1)
    print(a + ":" + data + name)
    time.sleep(1)
    print(a + ":" + age + data1 + data + name)
    time.sleep(1)
    print(a + ":" + name + data1 + data)
    time.sleep(1)
    print(a + ":" + age + data1 + data)
    time.sleep(1)
    print(a + ":" + age + data + data1)
    time.sleep(1)
    print(a + ":" + age + data1 + data)
    time.sleep(1)
    print(a + ":" + data1 + data + age)
    time.sleep(1)
    print(a + ":" + data + age + data1)
    time.sleep(1)
    print(a + ":" + age + age)
    time.sleep(1)
    print(a + ":" + name + name)
    time.sleep(1)
    print(a + ":" + data + age)
    time.sleep(1)
    print(a + ":" + data1 + age)
    time.sleep(1)
    print(a + ":" + data + data1 + age)
    time.sleep(1)
    print(a + ":" + age + data + data1 + name)

if age == "0":
    print("Обработка данных, подождите | Please wait")
    time.sleep(3)

    print(Fore.YELLOW)

    print(a + ":" + name + name1)
    time.sleep(1)
    print(a + ":" + name1 + name)
    time.sleep(1)
    print(a + ":" + data + name)
    time.sleep(1)
    print(a + ":" + data + name1)
    time.sleep(1)
    print(a + ":" + name + data1 + data)
    time.sleep(1)
    print(a + ":" + name1 + data1 + data)
    time.sleep(1)
    print(a + ":" + name1 + data + data1)
    time.sleep(1)
    print(a + ":" + name + name)
    time.sleep(1)
    print(a + ":" + name1 + name1)

if data == "0":
    print("Обработка данных, подождите | Please wait")
    time.sleep(3)

    print(Fore.YELLOW)

    print(a + ":" + name + age)
    time.sleep(1)
    print(a + ":" + name1 + age)
    time.sleep(1)
    print(a + ":" + age + name)
    time.sleep(1)
    print(a + ":" + age + name1)
    time.sleep(1)
    print(a + ":" + name + name1)
    time.sleep(1)
    print(a + ":" + name1 + name)
    print(a + ":" + age + age)
    time.sleep(1)
    print(a + ":" + name + name)
    time.sleep(1)
    print(a + ":" + name1 + name1)
    time.sleep(1)
    print(a + ":" + data1 + age)

if data1 == "0":
    print("Обработка данных, подождите | Please wait")
    time.sleep(3)

    print(Fore.YELLOW)

    print(a + ":" + name + age)
    time.sleep(1)
    print(a + ":" + name1 + age)
    time.sleep(1)
    print(a + ":" + age + name)
    time.sleep(1)
    print(a + ":" + age + name1)
    time.sleep(1)
    print(a + ":" + name + name1)
    time.sleep(1)
    print(a + ":" + name1 + name)
    time.sleep(1)
    print(a + ":" + data + name)
    time.sleep(1)
    print(a + ":" + data + name1)
    time.sleep(1)
    print(a + ":" + age + age)
    time.sleep(1)
    print(a + ":" + name + name)
    time.sleep(1)
    print(a + ":" + name1 + name1)
    time.sleep(1)
    print(a + ":" + data + age)

else:
    print("Обработка данных, подождите | Please wait")
    time.sleep(3)

    print(Fore.YELLOW)

    print(a + ":" + name + age)
    time.sleep(1)
    print(a + ":" + name1 + age)
    time.sleep(1)
    print(a + ":" + age + name)
    time.sleep(1)
    print(a + ":" + age + name1)
    time.sleep(1)
    print(a + ":" + name + name1)
    time.sleep(1)
    print(a + ":" + name1 + name)
    time.sleep(1)
    print(a + ":" + data + name)
    time.sleep(1)
    print(a + ":" + data + name1)
    time.sleep(1)
    print(a + ":" + age + data + data1 + name1)
    time.sleep(1)
    print(a + ":" + age + data1 + data + name)
    time.sleep(1)
    print(a + ":" + age + data1 + data + name1)
    time.sleep(1)
    print(a + ":" + name + data1 + data)
    time.sleep(1)
    print(a + ":" + name1 + data1 + data)
    time.sleep(1)
    print(a + ":" + name1 + data + data1)
    time.sleep(1)
    print(a + ":" + age + data1 + data)
    time.sleep(1)
    print(a + ":" + age + data + data1)
    time.sleep(1)
    print(a + ":" + age + data1 + data)
    time.sleep(1)
    print(a + ":" + data1 + data + age)
    time.sleep(1)
    print(a + ":" + data + age + data1)
    time.sleep(1)
    print(a + ":" + age + age)
    time.sleep(1)
    print(a + ":" + name + name)
    time.sleep(1)
    print(a + ":" + name1 + name1)
    time.sleep(1)
    print(a + ":" +data + age)
    time.sleep(1)
    print(a + ":" + data1 + age)
    time.sleep(1)
    print(a + ":" + data + data1 + age)
    time.sleep(1)
    print(a + ":" + age + data + data1 + name)

